### ISSUE TITLE
既然都发布到composer了，那psr系列规范也遵循起来吧

### ISSUE THREAD

**Issue by fatrbaby** [qq8044023/taskPHP#1]
个人觉得这不仅仅是一个风格和规范的问题。
psr系列规范在php的开发最佳实践上的探索是相当有价值的，现已成为了业界主流的规范了。
psr-4对业务与库的解耦上是有相当好处的，升级、扩战框架而不影响业务，这不正是我们所追求的么？

**Comment by qq8044023** [comment]
多谢你的意见，后续我们会规范 代码。
